<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pde_distribution"
 *
 * Auto generated by Extension Builder 2014-07-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'PanadeEdu Tutorial Distribution',
	'description' => 'Configures Template',
	'category' => 'example',
	'author' => 'Florian Tatzel',
	'author_email' => 'panadeedu@googlemail.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
			't3jquery' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);